baseurl = "https://rozrob.github.io/"
languageCode = "en-us"
title = "Hugo Creative Theme"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Roberto statybos"

		[params.navigation.links]
			about     = "Apie"
			services  = "Paslaugos"
			portfolio = "Atlikti darbai"
			contact   = "Kontaktai"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Statybos jūsų širdžiai"
		subtitle   = "-- Kliento ir architekto dialogas yra toks pat svarbus ir intymus kaip ir bet koks kitas pokalbis, nes kai kartu kalbame apie jūsų norimus atlikti ateities darbus, kalbame apie jūsų brangiausias ir gražiausias svajones."
		# subtitle   = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis nesciunt consequatur ut nihil voluptatem fugiat eos eveniet alias in veniam?"
		buttonText = "Susipažinkime"


	# About section
	[params.about]
		headline    = "Visokeriopa pagalba"
		description = "Jūsų norai, svajonės, įžvalgos, pamąstymai bus kruopščiai, realistiškai ir profesionaliai įvertinti pokalbio ar susitikimo metu. Po to suformuosime galimą numatyti darbų planą, jo struktūrą ir etapus bei atlikimo laiką ir kainą. Visados visomis įmanomomis priemonėmis stegsiuosi įgyvendinti užsibrėžtus tikslus ir mano bei jūsų džiaugsmui, savo turima ir nauja įgyjama patirtimi juos praturtinti ir įgyvendinti naujomis idėjomis."
		buttonText  = "Pradėkime!"


	# Service section
	[params.services]
		headline = "Mano paslaugos jums"

        [[params.services.list]]
            icon = "fa-home"
            title = "Statybos"
            description = "Atlieku visus įmanomus darbus, susijusius su statybomis."

        [[params.services.list]]
			icon = "fa-tree"
			title = "Parketas"
			description = "Šlifuoju, lakuoju, montuoju parketą su profesionalia įranga."

		[[params.services.list]]
            icon = "fa-tint"
            title = "Sodas"
            description = "Sodininkystė, apželdinimas, kraštovaizdžio kūrimas."

        [[params.services.list]]
            icon = "fa-heart"
            title = "Meilė darbui"
            description = "Darbai atliekami apgalvojant kiekvieną detalę, sutelktu dėmesiu, kruopščiai ir visada su šiluma!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Klientas"
        date = "Data"
        category = "Kategorija"
        buttonText = "Uždaryti"

    # Aside section
	[params.aside]
		headline = "Naujausias mano atliktų darbų nuotraukas galima peržiūrėti čia:"

		[params.aside.button]
			text = "Nuotraukų albumas"
			# link = "//github.com/digitalcraftsman/hugo-creative-theme"
			link = "#"

	# Contact section
	[params.contact]
		headline = "Susisiekime!"
		description = "Pasirengę pradėti savo norimą projektą kartu su manimi? Džiugu! Paskambinkite arba atsiųskite man el. laišką, ir aš kuo įmanoma greičiau susisieksiu su jumis!"
		phone = "+370 610 87516"
		email = "roberrtas@gmail.com"

	# Google Maps section
	[params.location]
	 	latitude  = "56.206965"
	 	longitude = "24.768313"
	    maps_api_key = "AIzaSyA7LOhThK91z9XGXQCCyuFEmHBkbBReiPY" # yep, i know, not secure...DC
